"use client";

/**
 * d1-report.ts
 *   - C-D46-4 (D-2 03시 슬롯, 2026-05-06) — Tori spec C-D46-4 (B-D46-3 / F-D46-4 / D-D46-5).
 *
 * Why: D+1 (5/9 09:00 KST) 회고 자동 .md 보고서. Roy 1클릭 다운로드 — 차트 0, 표 3종, 1 페이지.
 *   funnelEvents Dexie v10 read-only 누적 (24h 윈도우, RELEASE_ISO 기준).
 *
 * 정책:
 *   - read-only 의무 — 쓰기 호출 0 (write ops grep 0, verify-d46 gate 10).
 *   - BOM UTF-8 의무 — '﻿' prefix (UTF-8 인코딩 시 0xEF 0xBB 0xBF 3바이트, C-D46-3 정합).
 *   - RELEASE_ISO SoT 직접 import — '@/modules/dday/dday-config' (D-44-자-2 + D-45-자-1 사실 확정).
 *   - 한/영 헤더 분기 (locale param). 데이터는 동일.
 *   - 외부 dev-deps +0.
 */

import { RELEASE_ISO } from "@/modules/dday/dday-config";
import {
  getFunnel24hWithSpike,
  type FunnelKPIWithSpike,
} from "./funnel-kpi-query";
import type { Locale } from "@/modules/i18n/messages";

export interface D1ReportData {
  /** D+1 09:00 KST 시각 (RELEASE_ISO + 33시간 가량). */
  generatedAt: Date;
  /** 24h funnelEvents 누적 (C-D45-2 정합, 1σ_pop spike 정합). */
  kpi: FunnelKPIWithSpike;
  /** Show HN 점수 (Roy manual 입력 가능 — 미입력 시 'TBD'). */
  shownhScore?: number | string;
}

/**
 * D+1 회고 .md 본문 생성.
 *   BOM UTF-8 prefix + ASCII art 헤더 + 표 3종 + footer 워터마크.
 *   shownhScore 미입력 시 'TBD' 표시 (v1 정합 — 입력 UI 미구현).
 */
export function generateD1ReportMd(
  data: D1ReportData,
  locale: Locale = "ko",
): string {
  const { generatedAt, kpi, shownhScore } = data;
  const isKo = locale === "ko";
  const stamp = generatedAt.toISOString();
  const localStamp = isKo
    ? `${stamp.slice(0, 10)} ${stamp.slice(11, 16)} UTC`
    : `${stamp.slice(0, 10)} ${stamp.slice(11, 16)} UTC`;

  const headerArt = [
    "```",
    " ____            __                 __           ",
    "|  _ \\\\ ___    | _ )_ _ ___ _ _ ___\\\\ \\\\__ ___ _ _ ",
    "| (_) ) _ \\\\ _ | _ \\\\ '_/ _ \\\\ ' \\\\(_-< _\\\\__/ _ \\\\ '_|",
    "| .__/ \\\\___/(_)|___/_| \\\\___/_||_/__/_|  \\\\___/_|  ",
    "|_|              D+1  Report                      ",
    "```",
  ].join("\n");

  const releaseLine = isKo
    ? `**Release:** ${RELEASE_ISO}`
    : `**Release:** ${RELEASE_ISO}`;
  const generatedLine = isKo
    ? `**생성 시각:** ${localStamp}`
    : `**Generated:** ${localStamp}`;
  const windowLine = isKo
    ? `**24h 윈도우:** ${kpi.windowStart} → ${kpi.windowEnd}`
    : `**24h Window:** ${kpi.windowStart} → ${kpi.windowEnd}`;

  // Show HN 점수 표 (1행).
  const tbl1Title = isKo ? "## 1. Show HN 점수" : "## 1. Show HN Score";
  const scoreVal = shownhScore !== undefined ? String(shownhScore) : "TBD";
  const tbl1 = isKo
    ? `| 항목 | 값 |\n| --- | --- |\n| 점수 | ${scoreVal} |`
    : `| Metric | Value |\n| --- | --- |\n| Score | ${scoreVal} |`;

  // 24h 메시지 카운트 표 (5종 funnelEvents type — spike 빨강 ⚠️ 표시).
  const tbl2Title = isKo ? "## 2. 24h 메시지 카운트" : "## 2. 24h Message Counts";
  const tbl2Header = isKo
    ? "| 타입 | 카운트 | spike |"
    : "| Type | Count | spike |";
  const spikeMap = new Map(
    kpi.spikes.map((s) => [s.type, s.isSpike ? "⚠️" : "—"]),
  );
  const messageEntries = Object.entries(kpi.byType).filter(
    ([type]) => type !== "signup",
  );
  const tbl2Rows = messageEntries.length
    ? messageEntries
        .map(([type, count]) => `| ${type} | ${count} | ${spikeMap.get(type) ?? "—"} |`)
        .join("\n")
    : `| — | — | — |`;
  const tbl2 = `${tbl2Header}\n| --- | --- | --- |\n${tbl2Rows}`;

  // 24h 가입 카운트 표 (1행).
  const tbl3Title = isKo ? "## 3. 24h 가입 카운트" : "## 3. 24h Signups";
  const signupCount = kpi.byType["signup"] ?? 0;
  const tbl3 = isKo
    ? `| 항목 | 값 |\n| --- | --- |\n| 가입 | ${signupCount} |`
    : `| Metric | Value |\n| --- | --- |\n| Signups | ${signupCount} |`;

  const footer = `---\n_Generated by Robusta · ${localStamp}_`;

  // BOM UTF-8 prefix — '﻿' (UTF-8 인코딩 시 0xEF 0xBB 0xBF 3바이트, C-D46-3 정합).
  const md = [
    "﻿" + headerArt,
    "",
    releaseLine,
    "",
    generatedLine,
    "",
    windowLine,
    "",
    "---",
    "",
    tbl1Title,
    "",
    tbl1,
    "",
    tbl2Title,
    "",
    tbl2,
    "",
    tbl3Title,
    "",
    tbl3,
    "",
    footer,
    "",
  ].join("\n");

  return md;
}

/**
 * D+1 회고 다운로드 트리거.
 *   getFunnel24hWithSpike 호출 (read-only) → generateD1ReportMd → Blob 다운로드.
 *   파일명: robusta-d1-report-${YYYY-MM-DD}.md (UTC 기준).
 */
export async function downloadD1Report(
  locale: Locale = "ko",
  shownhScore?: number | string,
): Promise<void> {
  if (typeof window === "undefined") return;
  try {
    const kpi = await getFunnel24hWithSpike();
    const generatedAt = new Date();
    const md = generateD1ReportMd(
      { generatedAt, kpi, shownhScore },
      locale,
    );
    const fileDate = generatedAt.toISOString().slice(0, 10);
    const filename = `robusta-d1-report-${fileDate}.md`;
    const blob = new Blob([md], {
      type: "text/markdown;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.style.display = "none";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 0);
  } catch (err) {
    console.warn("[d1-report] download failed", err);
  }
}
