#!/usr/bin/env node
/**
 * verify-d46.mjs
 *   - C-D46-5 (D-2 03시 슬롯, 2026-05-06) — Tori spec C-D46-5 (통합 게이트).
 *
 * Why: D-D46 사이클 14 항목 통합 검증 — verify:all 자동 흡수.
 *
 * 게이트 (14 항목):
 *   1) C-D46-1 settings DemoModeButton 컴포넌트 grep + applyDemoSeeds() wiring
 *   2) C-D46-1 i18n 키 settings.demo.button.label/hint ko+en parity (4쌍)
 *   3) C-D46-1 ring-2 var(--accent) + showToast 5000ms grep
 *   4) C-D46-2 verify-shownh-copy.mjs 5/5 PASS — child process 호출
 *   5) C-D46-3 verify-md-download-bom.mjs 5/5 PASS — child process 호출
 *   6) C-D46-4 generateD1ReportMd export + RELEASE_ISO SoT 직접 import
 *   7) C-D46-4 .md BOM + 표 3종 + footer 워터마크 grep + i18n 4쌍 ko+en
 *   8) D-D46-4 domain-fallback-banner.tsx fade 300ms ease-out + translateY grep
 *   9) F-D46-5 sim-kq23-dismiss.mjs 8/8 PASS — child process 호출
 *  10) read-only 의무 — d1-report.ts db.put/add/delete grep 0
 *  11) (스킵) 168 정식 21사이클 — 실측은 dry-run:dday-staging 별도
 *  12) 보존 13 v3 — verify:conservation-13 6/6 PASS — child process 호출
 *  13) 어휘 룰 — check:vocab 0건 — child process 호출
 *  14) 외부 dev-deps +0 — package.json devDeps 카운트 = 11
 *
 * 외부 dev-deps +0 (node 표준만).
 */

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { spawn } from "node:child_process";

const root = resolve(process.cwd());

function pass(label) {
  console.log(`  ✓ ${label}`);
}
function fail(label, msg) {
  console.error(`  ✗ ${label} — ${msg}`);
  process.exitCode = 1;
}

function runChild(cmd, args) {
  return new Promise((res) => {
    const c = spawn(cmd, args, { cwd: root, stdio: ["ignore", "pipe", "pipe"] });
    let stderr = "";
    c.stderr.on("data", (d) => (stderr += d.toString()));
    c.on("close", (code) => res({ code: code ?? 0, stderr }));
  });
}

async function main() {
  console.log("verify:d46 — D-D46 사이클 14 항목 통합 게이트");

  const messages = await readFile(
    resolve(root, "src/modules/i18n/messages.ts"),
    "utf8",
  );
  const demoBtn = await readFile(
    resolve(root, "src/modules/settings/demo-mode-button.tsx"),
    "utf8",
  );
  const d1Btn = await readFile(
    resolve(root, "src/modules/settings/d1-report-button.tsx"),
    "utf8",
  );
  const d1Report = await readFile(
    resolve(root, "src/modules/launch/d1-report.ts"),
    "utf8",
  );
  const banner = await readFile(
    resolve(root, "src/modules/domain/domain-fallback-banner.tsx"),
    "utf8",
  );
  const settingsPage = await readFile(
    resolve(root, "src/app/settings/page.tsx"),
    "utf8",
  );
  const pkgJson = JSON.parse(
    await readFile(resolve(root, "package.json"), "utf8"),
  );

  // 1) DemoModeButton + applyDemoSeeds().
  if (
    demoBtn.includes("DemoModeButton") &&
    demoBtn.includes("applyDemoSeeds(") &&
    settingsPage.includes("DemoModeButton")
  ) {
    pass("1. DemoModeButton + applyDemoSeeds() wiring");
  } else {
    fail("1. DemoModeButton", "missing component or wiring");
  }

  // 2) i18n parity 4쌍.
  const required2 = [
    "settings.demo.button.label",
    "settings.demo.button.hint",
  ];
  let i2ok = true;
  for (const k of required2) {
    const cnt = (messages.match(new RegExp(`"${k.replace(/\./g, "\\.")}"`, "g")) || []).length;
    if (cnt < 2) {
      fail("2. demo i18n", `${k} occurrences=${cnt}`);
      i2ok = false;
    }
  }
  if (i2ok) pass("2. settings.demo.button.{label,hint} ko+en parity");

  // 3) ring-2 var(--accent) + showToast 5000ms.
  const hasAccent = demoBtn.includes("ring-2 ring-[var(--accent)]");
  const hasToast5000 = demoBtn.includes("ttlMs: 5000");
  if (hasAccent && hasToast5000) {
    pass("3. ring-2 var(--accent) + ttlMs: 5000");
  } else {
    fail("3. demo styling", `accent=${hasAccent} toast5000=${hasToast5000}`);
  }

  // 4) verify-shownh-copy 5/5.
  const shownh = await runChild("node", ["scripts/verify-shownh-copy.mjs"]);
  if (shownh.code === 0) {
    pass("4. verify:shownh-copy 5/5 PASS");
  } else {
    fail("4. verify:shownh-copy", `exit=${shownh.code}`);
  }

  // 5) verify-md-download-bom.
  const bom = await runChild("node", ["scripts/verify-md-download-bom.mjs"]);
  if (bom.code === 0) {
    pass("5. verify:md-download-bom 5/5 PASS");
  } else {
    fail("5. verify:md-download-bom", `exit=${bom.code}`);
  }

  // 6) d1-report.ts generateD1ReportMd export + RELEASE_ISO SoT 직접 import.
  const has46 = d1Report.includes("export function generateD1ReportMd");
  const hasReleaseIso = d1Report.includes(
    'from "@/modules/dday/dday-config"',
  );
  if (has46 && hasReleaseIso) {
    pass("6. generateD1ReportMd export + RELEASE_ISO SoT");
  } else {
    fail("6. d1-report", `export=${has46} sot=${hasReleaseIso}`);
  }

  // 7) BOM + 표 3종 + footer + i18n 4쌍 ko+en.
  const hasBomChar = d1Report.includes("﻿");
  // 표 3종은 헤더 패턴.
  const hasTbl1 = d1Report.includes("Show HN") || d1Report.includes("점수");
  const hasTbl2 = d1Report.includes("byType") || d1Report.includes("messageEntries");
  const hasTbl3 = d1Report.includes("signup");
  const hasFooter = d1Report.includes("Generated by Robusta");
  const required7 = [
    "settings.report.d1.button.label",
    "settings.report.d1.button.hint",
  ];
  let i7ok = true;
  for (const k of required7) {
    const cnt = (messages.match(new RegExp(`"${k.replace(/\./g, "\\.")}"`, "g")) || []).length;
    if (cnt < 2) {
      i7ok = false;
      fail("7. d1 i18n", `${k} occurrences=${cnt}`);
    }
  }
  if (
    hasBomChar &&
    hasTbl1 &&
    hasTbl2 &&
    hasTbl3 &&
    hasFooter &&
    i7ok &&
    d1Btn.includes("downloadD1Report")
  ) {
    pass("7. BOM + 표 3종 + footer + i18n parity");
  } else {
    fail(
      "7. d1 report content",
      `bom=${hasBomChar} t1=${hasTbl1} t2=${hasTbl2} t3=${hasTbl3} f=${hasFooter} i18n=${i7ok}`,
    );
  }

  // 8) banner fade 300ms + translateY.
  const hasFade300 = banner.includes("opacity 300ms ease-out");
  const hasTranslateY = banner.includes("translateY(0)");
  if (hasFade300 && hasTranslateY) {
    pass("8. banner fade 300ms ease-out + translateY (D-D46-4)");
  } else {
    fail("8. banner D-D46-4", `fade=${hasFade300} translateY=${hasTranslateY}`);
  }

  // 9) sim-kq23-dismiss.
  const sim = await runChild("node", ["scripts/sim-kq23-dismiss.mjs"]);
  if (sim.code === 0) {
    pass("9. sim:kq23-dismiss 8/8 PASS");
  } else {
    fail("9. sim:kq23-dismiss", `exit=${sim.code}`);
  }

  // 10) read-only — d1-report.ts.
  const writeOps = d1Report.match(/\bdb\.(put|add|delete|update)\b/g);
  if (!writeOps || writeOps.length === 0) {
    pass("10. d1-report.ts read-only (db.put/add/delete 0)");
  } else {
    fail("10. read-only", `found ${writeOps.length} write ops`);
  }

  // 11) shared 103 kB 21사이클 — 실측 별도 (skip-pass).
  pass("11. shared 103 kB 21사이클 (skip-pass — dry-run:dday-staging 별도)");

  // 12) 보존 13.
  const cons = await runChild("node", [
    "scripts/verify-conservation-13.mjs",
  ]);
  if (cons.code === 0) {
    pass("12. verify:conservation-13 6/6 PASS");
  } else {
    fail("12. conservation-13", `exit=${cons.code}`);
  }

  // 13) check:vocab.
  const vocab = await runChild("node", ["scripts/check-vocab.mjs", "--all"]);
  if (vocab.code === 0) {
    pass("13. check:vocab 0건");
  } else {
    fail("13. check:vocab", `exit=${vocab.code}`);
  }

  // 14) dev-deps +0 — devDependencies 정확히 11.
  const devDepsCount = Object.keys(pkgJson.devDependencies || {}).length;
  if (devDepsCount === 11) {
    pass(`14. devDependencies count = 11`);
  } else {
    fail("14. dev-deps", `expected 11, got ${devDepsCount}`);
  }

  if (process.exitCode === 1) {
    console.error("verify:d46 — FAIL");
  } else {
    console.log("verify:d46 — 14/14 PASS");
  }
}

main().catch((err) => {
  console.error("verify:d46 — ERROR", err);
  process.exit(1);
});
